[project]
name = "hopsworks-featurestore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hopsworks>=4.2.0",
    "pandas>=2.1.4",
]
